title: Talllinna Tehnikaülikooli Tarkvaraarenduse klubi Lapikud
email: about@lapikud.ee
description: > # this means to ignore newlines until "baseurl:"
  MTÜ Lapikud on Tallinna Tehnikaülikooli Tarkvaraarendusklubi, mis ühendab endisi ja praegusi IT huvilisi Tallinna Tehnikaülikooli üliõpilasi. Organisatsioon loodi 2002 aastal informaatika tudengite poolt, kelle erialatunnuseks oli "LAP". Targad mehed otsustasid, et järelikult on nad "Lapikud".
url: "http://lapikud.ee" # the base hostname & protocol for your site, e.g. http://example.com
instagram_username: lapikud
github_username:  lapikud
future: false
